---
- name: Add passwd,group,shadow files to the warewulf database
  command: wwsh file import /etc/passwd /etc/group /etc/shadow

- name: Create RegUser on OHPC
  user:
    name: "{{ RegUser_app_user }}"
    comment: "{{ RegUser_app_user_full_name }}"
    shell: /bin/bash
    createhome: yes
    home: /home/{{ RegUser_app_user }}
    state: present

- name: Create Cluster keys for RegUser on OHPC
  script: /usr/bin/cluster-env
  become_user: "{{ RegUser_app_user }}"

- name: WareWulf Sync for RegUser on OHPC
  command: wwsh file resync passwd group shadow
